# Generated by Django 3.0 on 2022-05-26 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonenumber', models.CharField(max_length=25, null=True)),
                ('balance', models.IntegerField(null=True)),
                ('loan', models.IntegerField(null=True)),
                ('reg_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='checkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30, null=True)),
                ('phonenumber', models.CharField(max_length=30, null=True)),
                ('amount', models.IntegerField(null=True)),
                ('reg_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Microfinance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('phonenumber', models.CharField(max_length=20, null=True)),
                ('city', models.CharField(max_length=30, null=True)),
                ('reg_date', models.DateField(auto_now_add=True)),
                ('level', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='session_levels',
            fields=[
                ('session_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('phonenumber', models.CharField(max_length=25, null=True)),
                ('level', models.IntegerField(null=True)),
            ],
        ),
    ]
