# Generated by Django 3.0 on 2022-06-02 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('title_en', models.CharField(max_length=10, null=True)),
                ('title_de', models.CharField(max_length=10, null=True)),
                ('title_tr', models.CharField(max_length=10, null=True)),
                ('content', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=30, unique=True)),
                ('slug_en', models.SlugField(max_length=30, null=True, unique=True)),
                ('slug_de', models.SlugField(max_length=30, null=True, unique=True)),
                ('slug_tr', models.SlugField(max_length=30, null=True, unique=True)),
            ],
        ),
    ]
