# Generated by Django 3.0 on 2022-06-02 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('content', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=30, unique=True)),
            ],
        ),
    ]
