# Generated by Django 3.0 on 2022-06-02 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lang', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='content_de',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='content_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='content_tr',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='slug_de',
            field=models.SlugField(max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='home',
            name='slug_en',
            field=models.SlugField(max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='home',
            name='slug_tr',
            field=models.SlugField(max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='home',
            name='title_de',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='title_en',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='title_tr',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
